# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170715_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='candidate',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='poll_id',
        ),
    ]
