# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170715_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll_id',
            new_name='poll',
        ),
    ]
